org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:TieredStopAtLevel=1
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.workers.max=4
android.useAndroidX=true
android.enableJetifier=true

kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx1g
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false