// File generated by FlutureFire CLI (ตัวอย่าง/placeholder — ไม่ใช่ค่าจริง)
//
// ไฟล์นี้เป็นตัวอย่างของ lib/firebase_options.dart ที่ .gitignore กันไว้
// (เพราะมีค่า config เฉพาะของ Firebase project จริง)
//
// วิธีใช้:
//   1) สร้าง Firebase project ของตัวเอง แล้วรัน `flutterfire configure`
//      เพื่อ generate lib/firebase_options.dart ของจริงให้อัตโนมัติ หรือ
//   2) คัดลอกไฟล์นี้ไปเป็น lib/firebase_options.dart แล้วแทนที่ค่า
//      placeholder ด้านล่างด้วยค่าจริงจาก Firebase console ของคุณ
//
// ใน CI ไฟล์นี้ถูกคัดลอกไปใช้ตรงๆ (ค่า placeholder พอสำหรับ `flutter analyze`
// และ `flutter test` เพราะเทสในโปรเจกต์นี้ไม่เรียก Firebase.initializeApp()
// จริง — ใช้ fake_cloud_firestore/firebase_auth_mocks แทนทั้งหมด)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: 'placeholder-app-id',
    messagingSenderId: 'placeholder-sender-id',
    projectId: 'placeholder-project-id',
    authDomain: 'placeholder.firebaseapp.com',
    storageBucket: 'placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: 'placeholder-app-id',
    messagingSenderId: 'placeholder-sender-id',
    projectId: 'placeholder-project-id',
    storageBucket: 'placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: 'placeholder-app-id',
    messagingSenderId: 'placeholder-sender-id',
    projectId: 'placeholder-project-id',
    storageBucket: 'placeholder.appspot.com',
    iosBundleId: 'com.example.energyHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: 'placeholder-app-id',
    messagingSenderId: 'placeholder-sender-id',
    projectId: 'placeholder-project-id',
    storageBucket: 'placeholder.appspot.com',
    iosBundleId: 'com.example.energyHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: 'placeholder-app-id',
    messagingSenderId: 'placeholder-sender-id',
    projectId: 'placeholder-project-id',
    storageBucket: 'placeholder.appspot.com',
  );
}