// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb5mtrhZKxaaNXVHBV-x2rLi4IZG2uRhU',
    appId: '1:382287446671:web:6194195f29e2725c1966fa',
    messagingSenderId: '382287446671',
    projectId: 'energy-home-e1c95',
    authDomain: 'energy-home-e1c95.firebaseapp.com',
    storageBucket: 'energy-home-e1c95.firebasestorage.app',
    measurementId: 'G-5TQV11VMM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZMtwUOP1VTLl4ac8rEXwxbrWOtaJqYQ',
    appId: '1:382287446671:android:a4110a8a84928b021966fa',
    messagingSenderId: '382287446671',
    projectId: 'energy-home-e1c95',
    storageBucket: 'energy-home-e1c95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9l1CAApa9ISdMa5Jd9KBXl9SklaE7Xeo',
    appId: '1:382287446671:ios:cf3b8f820820189d1966fa',
    messagingSenderId: '382287446671',
    projectId: 'energy-home-e1c95',
    storageBucket: 'energy-home-e1c95.firebasestorage.app',
    iosBundleId: 'com.example.energyHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9l1CAApa9ISdMa5Jd9KBXl9SklaE7Xeo',
    appId: '1:382287446671:ios:cf3b8f820820189d1966fa',
    messagingSenderId: '382287446671',
    projectId: 'energy-home-e1c95',
    storageBucket: 'energy-home-e1c95.firebasestorage.app',
    iosBundleId: 'com.example.energyHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb5mtrhZKxaaNXVHBV-x2rLi4IZG2uRhU',
    appId: '1:382287446671:web:87b20b346f887e571966fa',
    messagingSenderId: '382287446671',
    projectId: 'energy-home-e1c95',
    authDomain: 'energy-home-e1c95.firebaseapp.com',
    storageBucket: 'energy-home-e1c95.firebasestorage.app',
    measurementId: 'G-998QFC305T',
  );
}
